
package com.qiutt.webservice.jaxws.client.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IJaxWS", targetNamespace = "http://server.jaxws.webservice.qiutt.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IJaxWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.jaxws.webservice.qiutt.com/IJaxWS/byJaxWS1Request", output = "http://server.jaxws.webservice.qiutt.com/IJaxWS/byJaxWS1Response")
    public String byJaxWS1(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.jaxws.webservice.qiutt.com/IJaxWS/byJaxWSRequest", output = "http://server.jaxws.webservice.qiutt.com/IJaxWS/byJaxWSResponse")
    public String byJaxWS(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
